from binaryninja.enums import LowLevelILOperation

LLIL_REDIRECT = [   LowLevelILOperation.LLIL_JUMP,
					LowLevelILOperation.LLIL_JUMP_TO,
					LowLevelILOperation.LLIL_CALL,
					LowLevelILOperation.LLIL_RET,
					LowLevelILOperation.LLIL_NORET,
					LowLevelILOperation.LLIL_IF,
					LowLevelILOperation.LLIL_GOTO,
					LowLevelILOperation.LLIL_FLAG_COND,
					LowLevelILOperation.LLIL_CMP_E,
					LowLevelILOperation.LLIL_CMP_NE,
					LowLevelILOperation.LLIL_CMP_SLT,
					LowLevelILOperation.LLIL_CMP_ULT,
					LowLevelILOperation.LLIL_CMP_SLE,
					LowLevelILOperation.LLIL_CMP_ULE,
					LowLevelILOperation.LLIL_CMP_SGE,
					LowLevelILOperation.LLIL_CMP_UGE,
					LowLevelILOperation.LLIL_CMP_SGT,
					LowLevelILOperation.LLIL_CMP_UGT,
				]

LLIL_ARITHMETIC = [ LowLevelILOperation.LLIL_ADD,
					LowLevelILOperation.LLIL_ADC,
					LowLevelILOperation.LLIL_SUB,
					LowLevelILOperation.LLIL_SBB,
					LowLevelILOperation.LLIL_LSL,
					LowLevelILOperation.LLIL_LSR,
					LowLevelILOperation.LLIL_ASR,
					LowLevelILOperation.LLIL_ROL,
					LowLevelILOperation.LLIL_RLC,
					LowLevelILOperation.LLIL_ROR,
					LowLevelILOperation.LLIL_RRC,
					LowLevelILOperation.LLIL_MUL,
					LowLevelILOperation.LLIL_MULU_DP,
					LowLevelILOperation.LLIL_MULS_DP,
					LowLevelILOperation.LLIL_DIVU,
					LowLevelILOperation.LLIL_DIVU_DP,
					LowLevelILOperation.LLIL_DIVS,
					LowLevelILOperation.LLIL_DIVS_DP,
					LowLevelILOperation.LLIL_MODU,
					LowLevelILOperation.LLIL_MODU_DP,
					LowLevelILOperation.LLIL_MODS,
					LowLevelILOperation.LLIL_MODS_DP,
				]

LLIL_LOGIC = [  LowLevelILOperation.LLIL_NEG,
				LowLevelILOperation.LLIL_NOT,
				LowLevelILOperation.LLIL_AND,
				LowLevelILOperation.LLIL_OR,
				LowLevelILOperation.LLIL_XOR,
			]